spring:
  datasource:
    dynamic:
      primary: dev #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        dev:
          url: jdbc:mysql://msc01.dev1.fn:3306/rt_revert_01?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
          username: su_rt_revert
          password: sdfgrthtyjy
        beta:
          url: jdbc:mysql://ms-beta01.beta1.fn:3306/rt_revert_01?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
          username: su_rt_revert
          password: dmnvf62l9h
